WITH TLB AS (
SELECT
    
    PARENT_ID,
    COUNT(*) AS CNT
FROM ECOLI_DATA
GROUP BY PARENT_ID 
)

SELECT
    ED.ID,
    IFNULL(TLB.CNT, 0) AS CHILD_COUNT
FROM ECOLI_DATA AS `ED`
LEFT JOIN TLB ON ED.ID = TLB.PARENT_ID
