SELECT
    ID,
    CASE NTILE_DISTRIBUTE
        WHEN 1 THEN 'CRITICAL'
        WHEN 2 THEN 'HIGH'
        WHEN 3 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS COLONY_NAME
FROM (SELECT
        ID,
        NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS NTILE_DISTRIBUTE
     FROM ECOLI_DATA) AS temp
ORDER BY ID