WITH JULY_SUM_TLB AS (
    SELECT
        FLAVOR,
        SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR
), HALF_SUM_TLB AS (
    SELECT
        FLAVOR,
        SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM FIRST_HALF 
    GROUP BY FLAVOR        
), TOTAL_SUM_TLB AS (
    SELECT
        H.FLAVOR,
        H.TOTAL_ORDER + J.TOTAL_ORDER AS TOTAL_ORDER
    FROM HALF_SUM_TLB AS H
    INNER JOIN JULY_SUM_TLB AS J ON H.FLAVOR = J.FLAVOR
    GROUP BY H.FLAVOR
    ORDER BY TOTAL_ORDER DESC
)

SELECT
    T.FLAVOR
FROM TOTAL_SUM_TLB T
LIMIT 3

# SELECT
# *
# FROM TOTAL_SUM_TLB