SELECT
    G.SUM_SCORE AS `SCORE`,
    E.EMP_NO,
    E.EMP_NAME,
    E.POSITION,
    E.EMAIL
FROM HR_EMPLOYEES E
INNER JOIN (
    SELECT
        EMP_NO,
        SUM(SCORE) AS SUM_SCORE
    FROM HR_GRADE
    GROUP BY EMP_NO
) AS G
ON E.EMP_NO = G.EMP_NO
ORDER BY `SCORE` DESC
LIMIT 1