SELECT
    *
FROM 
    (SELECT
        CASE
        WHEN (D.SKILL_CODE & (SELECT SUM(`CODE`) FROM SKILLCODES WHERE CATEGORY LIKE 'Front%')) AND D.SKILL_CODE & (SELECT `CODE` FROM SKILLCODES WHERE NAME = 'Python') THEN 'A'
        WHEN (D.SKILL_CODE & (SELECT `CODE` FROM SKILLCODES WHERE NAME = 'C#')) THEN 'B'
        WHEN (D.SKILL_CODE & (SELECT SUM(`CODE`) FROM SKILLCODES WHERE CATEGORY LIKE 'Front%')) THEN 'C'
    END AS GRADE,
    ID,
    EMAIL
    FROM DEVELOPERS AS D) TEMP_TABLE
WHERE GRADE IS NOT NULL
ORDER BY GRADE, ID